spring:
  application:
    name: Doctor-zuul-api
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8100

#zuul:
  #routes:
    #doctors-service:
      #url: http://localhost:8082
    #patient-service:
      #url: http://localhost:8083
    #disease-service:
      #url: http://localhost:8081
  zuul:
    routes:
        service_1:
            path: /doctors-service/doctors/**
            url: http://localhost:8082/
        service_2:
            path: /patient-service/patients/**
            url: http://localhost:8083/
        service_3:
            path: /disease-service/diseases/**
            url: http://localhost:8081/

  host:
    connect-timeout-millis: 2000
    socket-timeout-millis: 5000

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    
